services:
  hath:
    image: ghcr.io/mixa3607/eh_hath:src_1.6.1
    environment:
      - HATH_CLIENT_ID=$HATH_CLIENT_ID
      - HATH_CLIENT_KEY=$HATH_CLIENT_KEY
      - HATH_PORT=$HATH_PORT
    volumes:
      - "./data/cache:/hath/cache"
      - "./data/data:/hath/data"
      - "./data/download:/hath/download"
      - "./data/log:/hath/log"
      - "./data/tmp:/hath/tmp"
    expose: 
      - $HATH_PORT
    ports: 
      - $HATH_PORT:$HATH_PORT
    stop_grace_period: 5m
    restart: unless-stopped
